export const UPDATE_DOUGH_VALUE = "UPDATE_DOUGH_VALUE";

export const UPDATE_SAUCE_VALUE = "UPDATE_SAUCE_VALUE";

export const UPDATE_SIZE_VALUE = "UPDATE_SIZE_VALUE";

export const UPDATE_NAME = "UPDATE_NAME";

export const DECREASE_INGREDIENT_COUNT = "DECREASE_INGREDIENT_COUNT";

export const INCREASE_INGREDIENT_COUNT = "INCREASE_INGREDIENT_COUNT";

export const SET_INGREDIENT_COUNT = "SET_INGREDIENT_COUNT";

export const ADD_TO_CART = "ADD_TO_CART";

export const ITEM_DROP = "ITEM_DROP";

export const DECREASE_PIZZA_COUNT = "DECREASE_PIZZA_COUNT";

export const INCREASE_PIZZA_COUNT = "INCREASE_PIZZA_COUNT";

export const SET_PIZZA_COUNT = "SET_PIZZA_COUNT";

export const CHANGE_SHOW_MODAL_STATUS = "CHANGE_SHOW_MODAL_STATUS";

export const FETCH_DOUGH = "FETCH_DOUGH";

export const FETCH_SIZES = "FETCH_SIZES";

export const FETCH_SAUCES = "FETCH_SAUCES";

export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS";

export const FETCH_MISC = "FETCH_MISC";

export const DECREASE_MISC_COUNT = "DECREASE_MISC_COUNT";

export const INCREASE_MISC_COUNT = "INCREASE_MISC_COUNT";

export const SET_MISC_COUNT = "SET_MISC_COUNT";

export const RESET_STORE = "RESET_STORE";

export const CHANGE_ACTIVE_SIDEBAR_MENU = "CHANGE_ACTIVE_SIDEBAR_MENU";

export const SET_EDITING_ADDRESS = "SET_EDITING_ADDRESS";

export const CHANGE_AUTH_STATUS = "CHANGE_AUTH_STATUS";

export const ADD_ORDER_MISC = "ADD_ORDER_MISC";

export const DELETE_ORDER = "DELETE_ORDER";

export const ADD_NEW_ORDER = "ADD_NEW_ORDER";

export const SET_DELIVERY_TYPE = "SET_DELIVERY_TYPE";

export const SET_DELIVERY_ADDRESS = "SET_DELIVERY_ADDRESS";

export const UPDATE_STREET_VALUE = "UPDATE_STREET_VALUE";

export const UPDATE_HOUSE_VALUE = "UPDATE_HOUSE_VALUE";

export const UPDATE_APARTMENT_VALUE = "UPDATE_APARTMENT_VALUE";

export const SET_EDITING_PIZZA = "SET_EDITING_PIZZA";

export const UPDATE_EXISTING_PIZZA = "UPDATE_EXISTING_PIZZA";

export const CLEAR_BUILDER_PROPERTIES = "CLEAR_BUILDER_PROPERTIES";

export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";

export const EDIT_ADDRESS = "EDIT_ADDRESS";

export const DELETE_ADDRESS = "DELETE_ADDRESS";
