export const UPDATE_DOUGH_VALUE = "UPDATE_DOUGH_VALUE";

export const UPDATE_SAUCE_VALUE = "UPDATE_SAUCE_VALUE";

export const UPDATE_SIZE_VALUE = "UPDATE_SIZE_VALUE";

export const UPDATE_NAME = "UPDATE_NAME";

export const DECREASE_INGREDIENT_COUNT = "DECREASE_INGREDIENT_COUNT";

export const INCREASE_INGREDIENT_COUNT = "INCREASE_INGREDIENT_COUNT";

export const SET_INGREDIENT_COUNT = "SET_INGREDIENT_COUNT";

export const ADD_TO_CART = "ADD_TO_CART";

export const ITEM_DROP = "ITEM_DROP";

export const UPDATE_TOTAL_PRICE = "UPDATE_TOTAL_PRICE";

export const DECREASE_PIZZA_COUNT = "DECREASE_PIZZA_COUNT";

export const INCREASE_PIZZA_COUNT = "INCREASE_PIZZA_COUNT";

export const SET_PIZZA_COUNT = "SET_PIZZA_COUNT";

export const CHANGE_SHOW_MODAL_STATUS = "CHANGE_SHOW_MODAL_STATUS";

export const FETCH_PIZZAS = "FETCH_PIZZAS";

export const FETCH_MISC = "FETCH_MISC";

export const DECREASE_MISC_COUNT = "DECREASE_MISC_COUNT";

export const INCREASE_MISC_COUNT = "INCREASE_MISC_COUNT";

export const SET_MISC_COUNT = "SET_MISC_COUNT";

export const RESET_STORE = "RESET_STORE";
